### ISSUE TITLE
Objets IFC : correspondances d'outils ALLPLAN

### ISSUE THREAD

**Issue by ALLPLANFRANCE** [bimstandards/bimstandards#50]
Bonjour,

Comment participer afin de renseigner les outils ALLPLAN?

Gabriel CASTEL

**Comment by alexandregrignon** [comment]
Bonjour,

Vous pouvez renseigner les outils Allplan dans le fichier suivant en renseignant le champ "_allplan:_" pour chaque classe d'objet IFC (attention à bien mettre un espace **après** les deux points) : https://github.com/bimstandards/bimstandards/blob/gh-pages/_data/ifc-objets.yml#L5

Si vous n'êtes pas familier de la plateforme GitHub, voici l'aide pour la modification d'un fichier : https://help.github.com/articles/editing-files-in-another-user-s-repository/

N'hésitez pas à me relancer si besoin.

**Comment by alexandregrignon** [comment]
ref #16

**Comment by ALLPLANFRANCE** [comment]
Merci, mise à jour effectuée pour les outils ALLPLAN. N'hésitez pas à me solliciter pour faire avancer votre projet sur les outils suivants:
ALLPLAN
Solibri
bim+

**Comment by alexandregrignon** [comment]
Merci pour votre aide, votre contribution est en ligne : http://bimstandards.fr/standards/objets-ifc/
