### ISSUE TITLE
Ajout de logiciels dans la page Outils

### ISSUE THREAD

**Issue by Ibex35** [bimstandards/bimstandards#66]
bonjour alexandre

sur http://bimstandards.fr/ressources/outils/

comment peut on ajouter des logiciels à ta liste?

aah , le rêve d'un éditeur: être référencé un peu partout!!!

Yves Ménez

**Comment by alexandregrignon** [comment]
Bonjour,
Il suffit de les ajouter dans ce fichier : https://github.com/bimstandards/bimstandards/blob/gh-pages/_data/outils.yml
Attention à bien respecter la mise en forme (copier-coller à partir des lignes existantes).
